// ⚠️ AUTOGENERATED ⚠️ AUTOGENERATED ⚠️ AUTOGENERATED ⚠️
// This file was automatically generated by `tools/gen-ts-glue.ts`. Do not modify directly if you want to keep your changes.
export * from "./src/VitePlugin";
import defaultExport from "./src/VitePlugin";
export default defaultExport;
